version: '3'

services:
  yolo-ncnn-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '3'  # Используем 3 ядра из 4 доступных на Raspberry Pi 4
          memory: 3G  # Ограничиваем использование памяти
    devices:
      - /dev/video0:/dev/video0  # Если нужен доступ к камере